
version: '3.1'

#networks:
#  default:
#    external: true
#    name: ${NETWORK:-dev-network}
volumes:
  data:
    driver: local


services:
  gen:
    image: s7i/doer:0.1.1-release_develop
    command:
     - /opt/doer/manifest/temperature-data01.yml
     - /opt/doer/manifest/temperature-data02-rnd.yml
    volumes:
      - ./data-gen:/opt/doer/manifest:ro
    environment:
      - DOER_LOG_APPENDER="CONSOLE"

  kafka:
    hostname: kafka
    build: ./kafka
    environment:
      - LOGS_DIR=/data/logs
    ports:
      - 7000:7000
      - 9092:9092
    volumes:
      - data:/data

  temp-anomaly:
    hostname: temp-anomaly
    build: .
    environment:
      - APP_BROKERS=kafka:9092
      - APP_JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DEBUG=ture
      - SPRING_PROFILES_ACTIVE=fixed
    ports:
      - 5005:5005
      - 8080:8080

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
