
version: '3.1'

#networks:
#  default:
#    external: true
#    name: ${NETWORK:-dev-network}
volumes:
  data:
    driver: local


services:
  gen: # https://github.com/sygnowski/doer/pkgs/container/doer/192577213?tag=0.1.1
    image: ghcr.io/sygnowski/doer:0.1.1
    command:
     #- /opt/doer/manifest/temperature-data-fixed.yml
     - /opt/doer/manifest/temperature-data-rand.yml
    volumes:
      - ./data-gen:/opt/doer/manifest:ro

  kafka:
    hostname: kafka
    build: ./kafka
    environment:
      - LOGS_DIR=/data/logs
    ports:
      - 7000:7000
      - 9092:9092
    volumes:
      - data:/data

  anomaly-detector:
    hostname: temp-anomaly
    build: .
    environment:
      - APP_BROKERS=kafka:9092
      - APP_JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DEBUG=false
      - app_anomaly_algName=alg2
      - spring_data_mongodb_uri=mongodb://anomaly-detector:pass2wd@mongo:27017/temperature-anomalies
    ports:
      - 5005:5005
      - 8080:8080

  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: temperature-anomalies
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
